version: '3'

services:
  app_django:
    build: .
    command: >
      /bin/sh -c "python3 manage.py makemigrations --force-color --no-input -v 3
      && python3 manage.py makemigrations --merge --no-input -v 3
      && python3 manage.py migrate --force-color -v 3
      && python manage.py runserver 0.0.0.0:8000"
    environment:
      SECRET_KEY: django-insecure-e+=tki09)$l187ppnj4uln&+bmlo12qfznl93!*d!wxbtxjc(v
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      ALLOWED_HOSTS: 80.249.146.99,anikeev-maks.ru,127.0.0.1:8000,127.0.0.1,localhost
      DEBUG: True
    ports:
      - '8000:8000'
